// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

type Category struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	VenueID   string             `json:"venue_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MenuItem struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	CategoryID  string             `json:"category_id"`
	VenueID     string             `json:"venue_id"`
	Price       pgtype.Numeric     `json:"price"`
	ImageUrl    string             `json:"image_url"`
	IsAvailable bool               `json:"is_available"`
	Description zero.String        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type QrLink struct {
	ID          string             `json:"id"`
	VenueID     string             `json:"venue_id"`
	TableNumber int32              `json:"table_number"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Description zero.String        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Password    string             `json:"password"`
	RoleID      string             `json:"role_id"`
	VenueID     string             `json:"venue_id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	PhoneNumber string             `json:"phone_number"`
	MiddleName  zero.String        `json:"middle_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Venue struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	VenueID     zero.String        `json:"venue_id"`
	LogoUrl     zero.String        `json:"logo_url"`
	Status      bool               `json:"status"`
	Description zero.String        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
