// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	zero "gopkg.in/guregu/null.v4/zero"
)

type Restaurant struct {
	ID          int64              `json:"id"`
	Uuid        zero.String        `json:"uuid"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	LogoUrl     zero.String        `json:"logo_url"`
	Status      bool               `json:"status"`
	Description zero.String        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Uuid        zero.String        `json:"uuid"`
	Title       string             `json:"title"`
	Description zero.String        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Uuid         zero.String        `json:"uuid"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	RoleID       int32              `json:"role_id"`
	RestaurantID int32              `json:"restaurant_id"`
	FullName     string             `json:"full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
