// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username,
    password,
    role_id,
    restaurant_id,
    full_name
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Password     string `json:"password"`
	RoleID       int32  `json:"role_id"`
	RestaurantID int32  `json:"restaurant_id"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.RoleID,
		arg.RestaurantID,
		arg.FullName,
	)
	return err
}
